export const SAVE_DEALER = 'SAVE_DEALER';
export const SAVE_RFQ = 'SAVE_RFQ';
export const SAVE_MULTILINE_IMAGE = 'SAVE_MULTILINE_IMAGE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const SAVE_UI_CONFIGS = 'SAVE_UI_CONFIGS';
export const CLEAR_RFQ_STATE = 'CLEAR_RFQ_STATE';
export const SAVE_MASTER_DETAILS = 'SAVE_MASTER_DETAILS';
export const SAVE_RFQ_DETAILS_RESPONSE = 'SAVE_RFQ_DETAILS_RESPONSE';
export const SET_FILE_PROGRESS = 'SET_FILE_PROGRESS';
export const RESET_FILE_UPLOAD = 'RESET_FILE_UPLOAD';

